on:
  push:
    branches:
      - 'feature/*'
jobs:
  create-pr:
    permissions: write-all       #permissions for the GITHUB-TOKEN
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Automated PR created by GitHub Actions'
          branch: ${{ github.ref }}
          base: main
          title: 'Automated PR for branch ${{ github.ref }}'
          body: 'Automated PR created by GitHub Actions for branch ${{ github.ref }}'
          labels: 'automated-pr'
