name: 'validate code'
env:
  GROUP_FOUND: 777

on:
  pull_request:
    branches:
    - 'main'
jobs:
  job1-validate:
    permissions: write-all       #permissions for the GITHUB-TOKEN
#      id-token: write
#      contents: read
#      issues: write      

    runs-on: 'ubuntu-latest'
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2.5.0

    # Install the latest version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3      

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1.1.0'

    - name: Install dependencies for python scripts
      run: |
        sudo apt-get install -y python3-pip
        pip3 install -r helpers/preconditions/requirements.txt

    - name: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ secrets.PROVIDER_NAME }} # this is the output provider_name from the TF module        
        service_account: ${{ secrets.SA_EMAIL }} # this is a SA email configured using the TF module with access to YOUR-GCS-BUCKET

    - name: 'check if scripts is there'
      run: ls ./terra-module/

    - name: 'run validation project script'
      run: ./helpers/preconditions/validate_projects.py

    - name: 'print value of GROUP_FOUND file'
      run: |
        echo "This is the value of result.txt file:"
        cat ./helpers/preconditions/result.txt
        result_var=$(cat ./helpers/preconditions/result.txt)
        file_details=$(cat ./helpers/preconditions/file_details.txt)
        echo $my_var        
        echo "RESULT_VAR=$result_var" >> $GITHUB_ENV
        echo "FILE_DETAILS=$file_details" >> $GITHUB_ENV

    - name: 'check the value of ENV variables'
      run: |
        echo "Group found value"
        echo ${{ env.RESULT_VAR }}
        echo "Group info"
        echo ${{ env.FILE_DETAILS }}

    - name: Create comment
      if: ${{ env.RESULT_VAR == 1 }}
      uses: mshick/add-pr-comment@v2
      with:
        message: |
          Failure, a project file is not valid. Go to actions tab for more details. ❌😕          

    - name: 'check validation'
      if: ${{ env.RESULT_VAR == 1 }}
      uses: actions/github-script@v6.3.3
      with:
        script: |
            core.setFailed('The project file is not valid: ${{ env.FILE_DETAILS }}')

    # Run Terraform init
    - name: Terraform Init
      id: init
      if: success()
      run: |
        cd terra-module
        terraform init 

    # Run a Terraform validate
    - name: Terraform validate
      id: validate
      if: success()       #it means run this step even either the previous step was success or failure   
      run: |
        cd terra-module
        terraform validate -no-color

    - name: Create comment
      if: failure()
      uses: mshick/add-pr-comment@v2
      with:
        message: |
          terraform validate failed. Go to actions tab for more details. ❌😕

    # Run a Terraform plan
    - name: Terraform plan
      id: plan
      if: success()
      run: |
        cd terra-module
        terraform plan -no-color

    # Add a comment to pull requests with plan results
    - name: Update Pull Request
      uses: actions/github-script@v6
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
          <details><summary>Show Plan</summary>
          \`\`\`\n
          ${process.env.PLAN}
          \`\`\`
          </details>
          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
